print("Hello world")
print("Nice to meet you Git")
print("I hope I can grasp you quickly")
name = input("So what's your name? ")
print("Hello,",name)
age = input("How old are you? ")
print("wow, you are already %s now !"%age)
